server:
  port: ${PORT:8067}
message: Configuracion de Categoria en el servidor levantado!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crudmicroservicios?serverTimezone=UTC
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
      database-platfomr: org.hibernate.dialect.MySQLDialect
