server:
    port: ${PORT:8063}
message: Configuracion de Coustomer en el servidor levantado!
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/crudcloud?serverTimezone=UTC
    username: root
    password: 123456789
    driver-class-name: con.mysql.cj.jdbc.Driver    
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
 
