server:
    port: ${PORT:8063}
message: Configuracion de Coustomer en el servidor levantado!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crudmicroservicios?serverTimezone=UTC
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
      database-platfomr: org.hibernate.dialect.MySQLDialect
 eureka:
  client:
    register-with-eureka: true
    #fetch-registry: false
    serviceurl:
      defaultZone: http://localhost:8761/eureka
