server:
    port: ${PORT:8063}
message: Configuracion de Coustomer en el servidor levantado!
spring:
  datasource:
    driver-class-name: con.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crudcloud?serverTimezone=UTC
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
      database-platfomr: org.hibernate.dialect.MySQLDialect
 
